### ISSUE TITLE
Question: How is the final VAF of variant calculated?

### ISSUE THREAD

**Issue by robinjugas** [bioinform/somaticseq#101]
We were looking over the results of somaticseq and we are interested in how the VAF of variant is calculated? Is it based on variant callers features or is it calculated direcly by somaticseq later? I haven't found anywhere in paper or manual. 
Thank you. 
Best regards, 
Robin Jugas

**Comment by litaifang** [comment]
The VAF field in the VCF file is estimated by SomaticSeq based on variant reads / (variant reads + reference reads). 
If there are multiple variants at one position, the "other" variant reads are not counted. If that case, you may also look into the .tsv file, and calculate directly (T_ALT_FOR+ T_ALT_REV)/T_DP. T_DP counts all mapped and deduped reads aligned to this position.

**Comment by robinjugas** [comment]
Thank you very much!
Best regards,
Robin Jugas
