### ISSUE TITLE
generating training data using single medium-coverage replicate of normal sample

### ISSUE THREAD

**Issue by kiranchari** [bioinform/somaticseq#106]
The recommendation to generate in-silico training data using a single _high-coverage_ normal sample is to split it (option 2 in https://github.com/bioinform/somaticseq/tree/master/somaticseq/utilities/dockered_pipelines/bamSimulator).

What do you recommend if the normal sample is not _high-coverage_? Can I increase the "split-proportion" greater than 0.5 (e.g. 0.80) so that each synthetic sample (syntheticNormal.bam and syntheticTumor.bam) has higher coverage even though they some reads will be assigned to both samples?

**Comment by litaifang** [comment]
You can use different split proportion. Usually tumor coverages would be higher than normal coverages. The split proportion will not have the same reads in both samples. 0.8 means 80% reads will be split into the normal and 20% of the reads will be split into the tumor. So something like 0.4 will split 60-40 for tumor-normal.
