### ISSUE TITLE
SV truthset for SEQC

### ISSUE THREAD

**Issue by miyakokodama** [bioinform/somaticseq#108]
Hi! I am writing regarding the document (https://github.com/bioinform/somaticseq/blob/seqc2_v1.2/docs/seqc2.md). Are you currently working on SV calling as well? If so, do you plan on publishing it in addition to SNV and indel truthsets?

Many thanks in advance,
Miyako Kodama

**Comment by litaifang** [comment]
We are currently working on the manuscript of multi-platform consensus SV call set. Hopefully it'll come out soon.
