### ISSUE TITLE
SomaticSeq - regex error

### ISSUE THREAD

**Issue by tinuthomas** [bioinform/somaticseq#11]
SomaticSeq issues with regex versions and getting the same error. Which version of regex is specifically required by SomaticSeq ?
2016.03.26,  regex-2016.4.8 and 2016.06.05
```/usr/local/bin/python3.4 somaticseq/modify_VJSD.py -method SomaticSniper -infile Sample1_SomaticSniper_SS.vcf -o CSample1_SomaticSniper_SS_modified.vcf
Traceback (most recent call last):
  File "/programs/ngsprograms/somaticseq_latest/somaticseq/modify_VJSD.py", line 15, in <module>
    import regex as reg
  File "/usr/local/lib/python3.4/site-packages/regex.py", line 683, in <module>
    _pattern_type = type(_compile("", 0, {}))
  File "/usr/local/lib/python3.4/site-packages/regex.py", line 545, in _compile
    parsed = parsed.optimise(info, reverse)
TypeError: optimise() takes 2 positional arguments but 3 were given
```

Would appreciate help

**Comment by ltfang-bina** [comment]
Is that the full error message?

I noticed that In the modify_VJSD.py file where the error seems to occur, the line should be "import regex as re" instead of the "import regex as reg" I'm seeing here. Did you make a change in the script?

**Comment by tinuthomas** [comment]
That was the only error message.

Meanwhile I changed to "import regex as re". Even now the error exists
/usr/local/bin/python3.4 somaticseq/modify_VJSD.py -method SomaticSniper -infile Sample1_SomaticSniper_SS.vcf -o Sample1_SomaticSniper_SS_modified.vcf
Traceback (most recent call last):
  File "/programs/ngsprograms/somaticseq_latest/somaticseq/modify_VJSD.py", line 15, in <module>
    import regex as re
  File "/usr/local/lib/python3.4/site-packages/regex.py", line 683, in <module>
    _pattern_type = type(_compile("", 0, {}))
  File "/usr/local/lib/python3.4/site-packages/regex.py", line 545, in _compile
    parsed = parsed.optimise(info, reverse)
TypeError: optimise() takes 2 positional arguments but 3 were given

**Comment by tinuthomas** [comment]
Error is a complaint from regex package the way it is taking arguments from modify_VJSD.py script

**Comment by ltfang-bina** [comment]
Seems like the modify_VJSD.py did not get past the import stage.
You may have run into this issue before: http://stackoverflow.com/questions/36729836/typeerror-with-python-regex-package. Have you tried to re-install the python and/or regex package?

**Comment by tinuthomas** [comment]
Tried re-installing the regex package twice and still getting the error. Also tried different versions of regex as specified in the first message, still no luck

**Comment by ltfang-bina** [comment]
Last resort, try commenting out the "import regex as re" line altogether, so the script will use python's default regex module. 
I prefer regex module because it has extra features, but for this script, the basic version may do. 
If that doesn't work, let me know.

**Comment by tinuthomas** [comment]
made "import regex" as "import re" in the following scripts and it worked.
somaticseq/modify_VJSD.py
somaticseq/genomic_file_handlers.py
somaticseq/pileup_reader.py
somaticseq/read_info_extractor.py


Thanks a lot for the support....
Have a great week ahead
