### ISSUE TITLE
Result of TNscope caller

### ISSUE THREAD

**Issue by yoda0612** [bioinform/somaticseq#111]
Hi, I am working with your somaticseq. 
I'd like to ask if I want to use the result of TNscope caller as the one of the inputs, how should I do?
Thank you.

**Comment by litaifang** [comment]
You can see all the available parameters before `paired` by command `somaticseq_parallel.py -h`, and all the available parameters after `paired` by command `somaticseq_parallel.py paired -h`. 
For TNscope, the argument would be `--tnscope-vcf tnscope_calls.vcf.gz`.

**Comment by yoda0612** [comment]
Thank you for your reply. 
Yes, as you mentioned the --tnscope-vcf seems worked only in "paired" mode. 
Is it possible to use --tnscope-vcf in "single" mode?

**Comment by litaifang** [comment]
I did not explicitly incorporate TNscope into the single mode. But in the latest version, there is a way to use the result of any additional caller, i.e., `--arbitrary-snvs` and `--arbitrary-indels`. 
First, you'll need to separate the snvs and indels by doing `splitVcf.py -infile TNscope.vcf.gz -snv tnscope_snvs.vcf -indel tnscope_indels.vcf`.

**Comment by yoda0612** [comment]
Thanks a lot
