### ISSUE TITLE
Docker issue with latest version

### ISSUE THREAD

**Issue by emucaki** [bioinform/somaticseq#115]
I am trying to use "BamSurgeon" which uses SomaticSeq, however there is an error that reaches that step:

docker run --rm -v /home/data:/home/data -u ####:#### lethalfang/somaticseq:latest \
java ...

"Error response from daemon: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: exec: "java": executable file not found in $PATH: unknown."

This problem does not happen when I use an older version of SomaticSeq:
docker run --rm -v /home/data:/home/data -u ####:#### lethalfang/somaticseq:3.6.3 \
java ...

Just wanted to let you know.

**Comment by litaifang** [comment]
Thanks for letting me know. 
I put java back into `lethalfang/somaticseq:latest`.
