### ISSUE TITLE
Question for the paper on establishing the reference call set

### ISSUE THREAD

**Issue by FriederikeHanssen** [bioinform/somaticseq#119]
Hi! 

I have recently read both papers on Establishing the reference call set and about the Best-practices and found them really interesting and helpful. We discussed the methods and I had a question for the WGS part of the reference call set:
As far as I understood you used PCR-free kits for it, right? Did you also use any of the WGS datasets with PCR for the reference call set?

Best and thank you! :)

**Comment by litaifang** [comment]
No, we did. 
Basically we used the best sequencing data we could get to establish the reference. Datasets with PCR is only used to see how it compares with the more sample-demanding PCR-free sequencing.

**Comment by litaifang** [comment]
To clarify an earlier typo, no we did not use anything other than PCR-free WGS data sets to establish the high-confidence call set.

**Comment by FriederikeHanssen** [comment]
Hi! Thank you very much for clarifying :)
