### ISSUE TITLE
TSV to VCF conversion

### ISSUE THREAD

**Issue by tinuthomas** [bioinform/somaticseq#12]
Trying to convert the SomaticSeq output to a VCF format and getting the following 

```
python3.4 somaticseq-2.2.1/SSeq_tsv2vcf.py -tsv Sample1_trained.tsv -vcf Sample-trained.vcf -pass 0.7 -low 0.1 -tools VarScan2 SomaticSniper MuSE -all -phred

File "somaticseq-2.2.1/SSeq_tsv2vcf.py", line 234, in <module>
    n_MQ0     = tsv_item[nBAM_MQ0]             if tsv_item[nBAM_MQ0]             != 'nan' else '.'
NameError: name 'nBAM_MQ0' is not defined

```

**Comment by ltfang-bina** [comment]
Is there a mismatch between the versions (i.e., .tsv file created with an earlier version, i.e., before v2.2.1)?
Previous to v2.2.1, there were nBAM_REF_MQ0 and nBAM_ALT_MQ0. I've found over time that MQ=0 are indicative of false positive calls, regardless of those MQ=0 reads support reference or variant. So by v2.2.1, I've merged those two metrics into nBAM_MQ0. 
But .tsv files created before v2.2.1 still had them separately as nBAM_REF_MQ0 and nBAM_ALT_MQ0, but v2.2.1's tsv2vcf.py looks for nBAM_MQ0 instead.
