### ISSUE TITLE
Where are the 10x Genomics single-cell copy number variation (CNV) analysis results?

### ISSUE THREAD

**Issue by genetronhealth** [bioinform/somaticseq#120]
Dear SEQC-II team, 

Thank you for the amazing amount of work that you have done to advance science.     
In Fig. 4b and Fig. 4c of the original NBT manuscript (https://www.nature.com/articles/s41587-021-00993-6), it mentions that you have sequenced both HCC1395 and HCC1395BL at single-cell level and shows copy-number heterogeneity at single-cell level. 
I woud like to simulate a tumor-normal mixture at single-cell level so that the copy number of each cell at each genomic locus is preserved, and this data look perfect to me except that I cannot find the raw copy-number results files. 
Hence, I would like to know where to find the copy-number results generated by the cell-ranger pipeline?

**Comment by yongmzhao** [comment]
@genetronhealth we can provide the raw copy-number results files if you let us know your contact information.
Thanks,
Yongmei

**Comment by zhaoxiaofei** [comment]
@yongmzhao You can send the raw copy-number results to cndfeifei AT aliyun DOT com , this email is supposed to be able to receive up to 60G of attachment. You can also send a download link to this email if it is more convenient to you. Thanks!

**Comment by genetronhealth** [comment]
@yongmzhao 

Sorry that I replied with another github account (I logged in as zhaoxiaofei using one web browser but as genetronhealth on another web brower). 

Just to confirm that you can send the raw copy-number results to ( cndfeifei AT aliyun DOT com ), this email is supposed to be able to receive up to 60G of attachment. You can also send a download link to this email if it is more convenient to you. Thanks!

CNV results that look similar to the ones at https://www.10xgenomics.com/resources/datasets/colo-829-g-1-sorted-1475-cells-1-standard-1-0-0 should be fine. 

Thank you!

**Comment by genetronhealth** [comment]
@yongmzhao 
Hello, is there any update on my request? 
If my request cannot be accomplished for any reason or if you would like to request any additional information, please let me know. 
Thanks.

**Comment by yongmzhao** [comment]
@genetronhealth 
I sent the files to  the email address you provided. Please email me if you have further questions.
Thanks.

**Comment by litaifang** [comment]
@genetronhealth have you gotten the files you needed?

**Comment by genetronhealth** [comment]
@litaifang 

Yes, I got the files that I needed so far. 
Some CNV calling tools require alignment to GRCh37 reference, but I probably will not use all tools. I may have to ask you more question if needed.   

Thank you for sharing your files! I closed this issue.
