### ISSUE TITLE
somaticseq failing for same command it had previously successfully run 

### ISSUE THREAD

**Issue by csreej27** [bioinform/somaticseq#122]
<img width="849" alt="image" src="https://github.com/bioinform/somaticseq/assets/119156694/fc014bf8-1fca-4ae5-9e9a-bd59a29acc2e">

I am getting the above error message for the below mentioned command , which has been in the past run and results successfully generated. 

`python3.7 /home/ec2-user/.local/bin/makeSomaticScripts.py paired --normal-bam /path/to/normal.bam --tumor-bam /path/to/tumor.bam --genome-reference /home/ec2-user/efs/sridhar/Somatic_resources/hg19/hg19.fa --inclusion-region /home/ec2-user/efs/sridhar/Somatic_resources/hg19/hg19_inclusion.bed --output-directory somaticseq_results_retrial_check --dbsnp-vcf /home/ec2-user/efs/sridhar/sreejita/hg19_dbsnp_sorted/new_sorted_dbsnp_138.hg19.vcf --threads 12 --container-tech  docker --run-mutect2 --run-vardict --run-lofreq --run-strelka2 --run-somaticseq--run-somaticsniper --run-varscan2 --run-workflow`

Although I don't understand why it is saying somaticseq distribution not found because when I just type the following  `python3.7 /home/ec2-user/.local/bin/makeSomaticScripts.py paired --help` 
The help page pops up perfectly well : 
<img width="614" alt="image" src="https://github.com/bioinform/somaticseq/assets/119156694/d18a36c6-4df0-42ba-91df-08f0bfe8fcbf">

**Comment by litaifang** [comment]
What if you just try to install somaticseq and invoked `makeSomaticScripts.py` directly (without invoking the full path like `python3.7 /home/ec2-user/.local/bin/makeSomaticScripts.py`)?

**Comment by csreej27** [comment]
Hi , as per your suggestion, I invoked makeSomaticScripts.py directly - and now I am getting the following error : 
<img width="770" alt="image" src="https://github.com/bioinform/somaticseq/assets/119156694/5987cb92-cbde-42ba-a3e8-ca83e1cef2ac">

**Comment by csreej27** [comment]
Hi, 
As per your suggestion I invoked makeSomaticScripts.py directly and now I am getting the following error : 
<img width="691" alt="image" src="https://github.com/bioinform/somaticseq/assets/119156694/b3865d15-4348-4338-b02e-faf48bb9dda4">

**Comment by litaifang** [comment]
2 Questions:
- Does the hg19.fa have associated hg19.fa.fai and hg19.dict in the same directory?
- Is bedtools installed and callable in the instance?

**Comment by litaifang** [comment]
You also had `--run-somaticseq--run-somaticsniper` without space in them. Don't know if that was your actual command and if that made any difference.

**Comment by csreej27** [comment]
- the hg19.fa does have the associated hg19.fa.fai and hg19.dict in the same directory
- yes, bedtools is installed and can be invoked directly from anywhere in the instance 
- "--run-somaticseq--run-somaticsniper without space" - I believe this might just been a typing error while posting the issue here because I checked my scripts and there was space in there

**Comment by litaifang** [comment]
That's weird.... can you copy-and-paste the actual script?

**Comment by csreej27** [comment]
Below was my command : 

` makeSomaticScripts.py paired --normal-bam /path/to/normal.bam --tumor-bam /path/to/tumor.bam --genome-reference /path/to/hg19/hg19.fa --inclusion-region /path/to/hg19/hg19_inclusion.bed --output-directory test_out_dir --dbsnp-vcf /path/to/hg19_dbsnp_sorted/new_sorted_dbsnp_138.hg19.vcf --threads 12 --container-tech  docker --run-mutect2 --run-vardict --run-lofreq --run-strelka2 --run-somaticseq --run-somaticsniper --run-varscan2 --run-workflow`
Do you want me to send you my actual bash script ?

**Comment by litaifang** [comment]
Try creating the output directory `somaticseq_results_retrial_check`. That may be the problem. makeSomaticScripts.py will not create the output_directory if it does not exist already.

**Comment by csreej27** [comment]
Hi, 
So somaticseq ran and gave results successfully after two measures you suggested : 

1. invoking script directly ( without mentioning full path ) 
2. creating the output directory prior to running the script 

So thank you for suggesting those measures, I really appreciate it . 

However I would like to point out that  we have faced several concerns over the past year with somaticseq - around its stability . It would be great if you could please look into it

**Comment by litaifang** [comment]
In terms of stability, are those docker issues or somaticseq issues?
