### ISSUE TITLE
Applying internal filters to outputs before running SomaticSeq

### ISSUE THREAD

**Issue by ronkesm** [bioinform/somaticseq#123]
Hi,

I was wondering how useful it is to apply the internal filters of SomaticSniper, Varscan2, mutect2 etc. before inputting them into SomaticSeq? I compared outputs from CaVEMan (alone) and SomaticSeq with filtered Varscan2 + SomaticSniper and Muse and found that variants under 0.1 VAF were completely absent from the latter (even though it is relatively high coverage data ~60-70X).

Thanks

**Comment by litaifang** [comment]
Depends.....
I usually don't filter for each caller before hand. I can always filter them afterwards. Once aggregated from all the callers and features extracted from the bam files, there are additional criteria you can decide on.
