### ISSUE TITLE
adding Strelka

### ISSUE THREAD

**Issue by ramaniak** [bioinform/somaticseq#18]
Hello,
I am using somaticseq for carrying out ensembl calling on my tumour-normal paired exome data. I am also using Strelka as one of my somatic callers and don't see it as one of the options. Is there any development going on to incorporate strelka into the mix? 

If I were to try and modify the code myself, are there any points to keep in mind so as to not break any functionality?

thanks
Arun

**Comment by ltfang-bina** [comment]
We don't have Strelka license. 
Maybe you can send me an example Strelka VCF file to li_tai.fang@bina.roche.com, and I'll take a look if it's simple to incorporate it.

**Comment by ltfang-bina** [comment]
Strelka2 is now incorporated into SomaticSeq's repo. It'll be available in the next release, i.e., v2.2.3, or the current source code.
