### ISSUE TITLE
updates to data download page

### ISSUE THREAD

**Issue by 0xaf1f** [bioinform/somaticseq#22]
On http://bioinform.github.io/somaticseq/data.html

- Linked instructions to GeneTorrent now say to use Bionimbus instead. It might be better to point directly to those new instructions.
- SomaticSpike: "We will include the link to the spiked BAM files when they are done uploading". Maybe an update is needed here.
- Analysis Files - both links are broken.

**Comment by ltfang-bina** [comment]
Thanks for the heads up. 

* I'll check a bit later how to get the DREAM Challenge data after they changed those instructions. 
* SomaticSpike data together are a few hundred gigabytes. The interest in them are quite minimal. The last person who requested it, he shipped us a hard drive, and we copied and shipped the hard drive back to him. That's probably a better bet, and I'll change the instruction for that. 
* For the analysis files, our Google drive associated with Bina Technologies are gone. I'll have to find a way to host them elsewhere.

**Comment by ltfang-bina** [comment]
I couldn't find the DREAM challenge data sets for the longest time, but it seems they're here:
https://console.cloud.google.com/storage/browser/public-dream-data/
