### ISSUE TITLE
Question: true set?

### ISSUE THREAD

**Issue by apastore** [bioinform/somaticseq#25]
Hi I was looking in your somatiseq. I have a quite naive question what do you suggest to use as a true snp and Indel vcf for model training. Let's say I have some new patient their mutation status is unknown. How can I generate the true set in a practical way? 
Thanks a lot for your suggestions!

**Comment by ltfang-bina** [comment]
Say you have 100x tumor and 50x matched normal. You can try this:
1) Merge the tumor and normal data into a single 150x BAM file. You may need to reheader so they have the same sample name.
2) Use BAMSurgeon (https://github.com/adamewing/bamsurgeon) to randomly split the 150x BAM into into a 50x designated normal and 100x designated tumor. (If you run your tool on that data set, every somatic call will be labeled as a false positive.)
3) Use BAMSurgeon to spike in mutations as true positives to the designated tumor BAM. There, you have a training set with ground truth from BAMSurgeon.

**Comment by apastore** [comment]
Thanks for your suggestions!

How many mutations would you suggest to spike in? This are in-silico variants or derived from my tumors?

Are you planing to write a wrapper to take care of the training set generation?

Thanks!
Alessandro

**Comment by ltfang-bina** [comment]
How many mutation you want to spike in depends on the tumor type you're analyzing. You probably want the same order of magnitude, if the capture region is 50 MBp, probably no more than 1 per 100 kbps, so about 500. The sites are chosen at random. 

It's a good idea to write a wrapper for that, but we probably won't do that until the next time we do something like this ourselves. It probably won't happen until the 2nd half of this year.

**Comment by apastore** [comment]
Thanks a lot for your suggestions!

maybe you can mark this as enhancement and come back at the point you all need a true set!
Thanks!

**Comment by ltfang-bina** [comment]
We have finally created a wrapper scripts for BAMSurgeon simulation, i.e., semi-simulated data set that can be used for training: https://github.com/bioinform/somaticseq/tree/master/utilities/dockered_pipelines/bamSurgeon/singleThread
For now,  it's only for exome (i.e., single-thread, without parallelization). 
It's quite rudimentary right now. We'll add more features and flexibilities as we keep testing/using it.
