### ISSUE TITLE
is it possible to support both mutect and mutect2

### ISSUE THREAD

**Issue by hongenxu** [bioinform/somaticseq#28]
Hi Dr. Fang, 

in the manual,  you mentioned that, 
```
If both MuTect2 and MuTect/Indelocator VCF les are provided, the script is written such
that it will use MuTect2 and ignore MuTect.
```
since SNV calls of mutect and mutect2 are very different (http://gatkforums.broadinstitute.org/gatk/discussion/6794/difference-between-mutect-1-1-7-and-mutect2), it makes sense to join them together. 

Best,
Hongen

**Comment by ltfang-bina** [comment]
I guess it's possible for you to manually join MuTect and MuTect2 together using something like GATK CombineVariants, and the software will handle them fine. 
Handling the two call sets as separate callers isn't a super-high priority at this moment.

**Comment by ltfang-bina** [comment]
I guess it's possible for you to manually join MuTect and MuTect2 together using something like GATK CombineVariants, and the software will handle them fine. 
Handling the two call sets as separate callers isn't a super-high priority at this moment.
