### ISSUE TITLE
hg19 and b37

### ISSUE THREAD

**Issue by zyywmy** [bioinform/somaticseq#43]
Can I train a model using all the b17 files and then predict somatic variants using hg19 files? Same question about the opposite way? Thanks,

**Comment by ltfang-bina** [comment]
Should not be a big deal to go from one reference to another. The model/classifier doesn't know what reference it came from. 
Theoretically speaking, if the reads map very differently from one reference to another, the model could be different, but I think the difference between different versions of the human genome is minuscule.
