### ISSUE TITLE
No sample information error

### ISSUE THREAD

**Issue by zyywmy** [bioinform/somaticseq#46]
Hi, I tried to run SomaticSeq.Wrapper.sh to combine four VCF files.
I got following error:
Traceback (most recent call last):
  File "~/modify_VJSD.py", line 269, in <module>
    raise Exception('No sample information here.')
Exception: No sample information here.
I checked that one VCF file called from lofreq has no sample column. Is this the reason? But some other samples are running well even with the lofreq VCFs without sample column.

**Comment by ltfang-bina** [comment]
LoFreq does not output sample names so that shouldn't be a problem. modify_VJSD.py is not run on LoFreq's output anyway. 

Can you show me the SomaticSeq.Wrapper.sh command?

**Comment by zyywmy** [comment]
My command line is:
~/resource/somaticseq/SomaticSeq.Wrapper.sh --mutect merged_Breast_Breast_4_Tumor_all.vcf --muse merged_Breast_Breast_4_Tumor_all.vcf --lofreq-snv merged_Breast_Breast_4_Tumor_all.vcf --strelka-snv ./4_Tumor/results/variants/somatic.snvs.vcf.gz --normal-bam Breast_Breast_4_Normal.bam --tumor-bam Breast_Breast_1004_Tumor.bam --genome-reference ~/Resources/Data/genome/hg19_canonical_correct_chr_order.fa --cosmic ~/hg19/cosmic_v67.hg19.vcf --dbsnp ~/hg19/dbsnp_138.hg19.vcf.gz --gatk ~/resource/GenomeAnalysisTK.jar --output-dir ~/Results/voting/Breast_Breast_1004_Tumor_4callers
Thanks!

**Comment by ltfang-bina** [comment]
Did you have the same file "merged_Breast_Breast_4_Tumor_all.vcf" for all the tools (e.g., --mutect, --muse, etc.)?
Those flags are meant for VCF files created by each of these tools.

**Comment by zyywmy** [comment]
Sorry the confuse. The VCF files merged_Breast_Breast_4_Tumor_all.vcf are different and got different callers, actually are placed in different folders (I just removed the folder names in the above command line).

**Comment by ltfang-bina** [comment]
I'm wondering if you pointed each of these VCF files to the correct tool prefixes. 
Can you send me those VCF files? Or send me the first ~ 10 lines of those VCF files (including the ## headers) and see what's causing the problem?

**Comment by zyywmy** [comment]
It's interesting that I could not repeat this error if only take first 100 records and the headers of the Muse VCF file. I found it's running OK if using all other original/truncated VCF files and that truncated Muse VCF file but it always failed when using the Muse original VCF file. So, it seems that the problem is caused by the muse original file. Could you find the reason?

**Comment by zyywmy** [comment]
It seems that the reason is there are malformatted lines in the MUSE original VCF file. I'll check the Muse calling. Thanks anyway!

**Comment by ltfang-bina** [comment]
Just to be sure, MuSE has two steps. Each step produces an output. 
1) MuSEv1.0rc_submission_c039ffa call -O /PATH/TO/MuSE -l bed_3columns.bed -f /PATH/TO/GRCh38.fa /PATH/TO/HCC1395.bam /PATH/TO/HCC1395BL.bam
2) MuSEv1.0rc_submission_c039ffa sump -I PATH/TO/MuSE.MuSE.txt -G -O /PATH/TO/**MuSE.calls.vcf** -D /PATH/dbsnp_146.hg38.vcf.gz

The 1st step produces MuSE.MuSE.txt.
The 2nd step produces MuSE.calls.vcf

Are you using the 2nd output?

You may also send me your MuSE VCF file if you don't mind, and I'll check what's causing the problem.

**Comment by zyywmy** [comment]
Yes, I'm using the 2nd output. Eventually, I found out the error was happened when I was filtering the Muse VCFs using "PASS". Maybe two processes were writing to a same file concurrently.

**Comment by ltfang-bina** [comment]
If you grep 'PASS', you'll miss the "#CHROM" line that has the sample information. 
Although SomaticSeq already takes "PASS" label into account.

**Comment by zyywmy** [comment]
I grabbed both header # lines and PASS lines from the original MUSE VCF file. And now it works fine. 
But I got two errors during execution of above command line:
1. An error message (from GATK) at the end of execution. (see below) Do you know the reason?
##### ERROR ------------------------------------------------------------------------------------------
##### ERROR A USER ERROR has occurred (version nightly-2016-05-23-g1fee024):
##### ERROR
##### ERROR This means that one or more arguments or inputs in your command are incorrect.
##### ERROR The error message below tells you what is the problem.
##### ERROR
##### ERROR If the problem is an invalid argument, please check the online documentation guide
##### ERROR (or rerun your command with --help) to view allowable command-line arguments for this tool.
##### ERROR
##### ERROR Visit our website and forum for extensive documentation and answers to
##### ERROR commonly asked questions https://www.broadinstitute.org/gatk
##### ERROR
##### ERROR Please do NOT post this error to the GATK forum unless you have really tried to fix it yourself.
##### ERROR
##### ERROR MESSAGE: Argument with name '--variant' (-V) is missing.
##### ERROR ------------------------------------------------------------------------------------------

2. Another issue is at the mid of execution of command line:
.../python3/3.5.1-shared/lib/python3.5/site-packages/scipy/stats/stats.py:4938: RuntimeWarning: invalid value encountered in double_scalars. 
Is the python version issue? Will that affect the results?

**Comment by ltfang-bina** [comment]
Via email communication:
That error occurs because there is no indel file, but SomaticSeq.Wrapper.sh assumes there are indel files and continued on. 
This error no longer occurs from version v2.5.0 as onward.
