### ISSUE TITLE
Could you provide documentation on the 70 features extracted by somaticseq? Trying to better understand SomaticSeq's model

### ISSUE THREAD

**Issue by kiranchari** [bioinform/somaticseq#48]

**Comment by ltfang-bina** [comment]
You can probably just look at this script https://github.com/bioinform/somaticseq/blob/master/SSeq_merged.vcf2tsv.py
Starting line #137 is the part of the header whose features are being used. 
The same is also shown at the very end of the script. Most of the header names are pretty descriptive.

**Comment by ltfang-bina** [comment]
Let me know if you need more information. 
The number of features is closer to 100 than 70 now.
