### ISSUE TITLE
SomaticSeq.Wrapper.sh should support GATK4

### ISSUE THREAD

**Issue by 0xaf1f** [bioinform/somaticseq#52]
Currently, part of the pipeline requires GATK4 and another (the wrapper) uses GATK3. To avoid needing two GATK installations to run the whole pipeline, it'd be best to update the wrapper to use GATK4.

this was discussed in https://github.com/bioinform/somaticseq/pull/50. This ticket is for tracking purposes.

**Comment by ltfang-bina** [comment]
As v2.7.1, SomaticSeq.Wrapper.sh will use utilities/getUniqueVcfPositions.py and utilities/vcfsorter.pl (in lieu of GATK3 CombineVariants) to combine all the VCF files (do not invoke --gatk option in the wrapper script, which is still only compatible with GATK3).
