### ISSUE TITLE
Normalized multiallelic indels in CombineVariants_MVJSD.indel.vcf excluded from Ensemble.tsv

### ISSUE THREAD

**Issue by pkothiyal** [bioinform/somaticseq#56]
Hello, 

While evaluating somaticseq for majority voting for Indels, I ran into an issue. Here's an example of how an Indel called in at least one caller is missed due to variant normalization with GATK CombineVariants.

The calls from two callers at the position are:
```
strelka.indel.vcf:1	76786670	.	TTA	T	.	QSI_ref
strelka.indel.vcf:1	76786670	.	T	TTA	.	PASS
mutect.indel.vcf:1	76786670	.	TTA	T	. alt_allele_in_normal;germline_risk;str_contraction
```
The resulting entry in the merged VCF produced by GATK CombineVariants is:
`CombineVariants_MVJSD.indel.vcf:1	76786670	.	TTA	T,TTATA	.	PASS`

CombineVariants has normalized the variants here to create a multi-allelic record in the merged VCF where one is an insertion and one is a deletion. 

As I understand, in the next step to get Ensemble.sIndel.tsv from this merged VCF, each allele in multiallelic ALT is treated separately and has its own row in the TSV file if the number of tools with a PASS call for that variant is > `mincaller` (hardcoded as 0.5 in SomaticSeq.Wrapper.sh), the record is printed to Ensemble.sIndel.tsv and otherwise it's excluded completely. 

In this case, the two variants it looks for after splitting multiallelic ALT are:

```
1:76786670:TTA>T 
1:76786670:TTA>TTATA
```

Now this is where the problem occurs. The first variant is not PASS in any of the callers so it's not printed. The second is a PASS in Strelka but it is represented as `1:76786670:T>TTA` in Strelka VCF. somaticseq looks for the normalized indel in the original VCF and does not find the record so the variant is not printed from this point on.

Do you have any suggestions on how to work around this?

Thanks,
Prachi

**Comment by ltfang-bina** [comment]
You can try v2.7.1 or newer, and run the Wrapper.sh script **without** the --gatk argument. It will bypass GATK CombineVariants, and instead use utilities/getUniqueVcfPositions.py and vcfsorter.pl to merge VCF files. It's a simple method to combine all the unique (CONTIG, POSITION, REF, ALT) without doing anything extra.

**Comment by pkothiyal** [comment]
Thank you. I will try it out.

**Comment by ltfang-bina** [comment]
Workaround appears to be found.
