### ISSUE TITLE
Arguments for each caller 

### ISSUE THREAD

**Issue by Tato14** [bioinform/somaticseq#58]
I am running the different callers in order to have the vcf files for each. I was wondering if there is any differences in the arguments that you specify in the methods of your article. 

Thanks!

**Comment by ltfang-bina** [comment]
When you run scripts here, you can see the parameters being written to the run scripts:
https://github.com/bioinform/somaticseq/tree/master/utilities/dockered_pipelines

To see the parameters used for the publications ~ 2 years ago, you can download the very first version of this repo (https://github.com/bioinform/somaticseq/archive/1.0.tar.gz), and see Run_5_callers/Step_2_Run_5_tools.sh.
