### ISSUE TITLE
Please release a version

### ISSUE THREAD

**Issue by rhpvorderman** [bioinform/somaticseq#61]
Dear maintainers,

Thank you for this nice program. Can you release a version (using for example git tag) so SomaticSeq can be used reproducibly? We can then refer to the version in papers etc.

Also, I was planning to package this program into [Bioconda](http://bioconda.github.io/). This requires a version. It will make it easier for people to install your package and easier to integrate it in to our pipelines here at the institute.

So if you could please release a version, I will make sure it is packaged. Thanks in advance!

**Comment by rhpvorderman** [comment]
Whoops. Looked at the wrong repo. Sorry!

**Comment by ltfang-bina** [comment]
Anyway, my current branch actually has some major improvements from the ones that were tagged as releases. So if you'd like to package that, let me know and I can release the newest version.....
