### ISSUE TITLE
Error with somaticseq_parallel.py

### ISSUE THREAD

**Issue by joonlee3** [bioinform/somaticseq#68]
Hi,

   I tried to run somaticseq (v3.2.1) with the following command line

    ~/.pyenv/versions/3.6.1/bin/python ${SomaticSeq_home}/somaticseq_parallel.py paired \
    -outdir ${vcf_output_path}/SomaticSeq_new \
    --genome-reference /site/ne/home/wings/ref_data/reference_genome/hg19/hg19_decoy/hg19.decoy.fa \
    -nbam ${bam_n} \
    -tbam ${bam_t} \
    --threads 8 \
    --mutect2-vcf ${tumour_id}.mutect2.pass.vcf \
    --vardict-vcf ${tumour_id}.vardict.pass.vcf \
    --strelka-snv ${tumour_id}.strelka2.snvs.pass.vcf \
    --strelka-indel ${tumour_id}.strelka2.indels.pass.vcf

At the end, I've got the following error - somaticseq_parallel.py: error: the following arguments are required: -ref/--genome-reference

If you have suggestions, please let me know.

Thank you,
Joon

**Comment by ltfang-bina** [comment]
Hi Joon, 

The options/arguments for `-outdir` and `--genome-reference` should be placed before **paired**. 

Try, 
```
~/.pyenv/versions/3.6.1/bin/python ${SomaticSeq_home}/somaticseq_parallel.py \
-outdir ${vcf_output_path}/SomaticSeq_new \
--genome-reference /site/ne/home/wings/ref_data/reference_genome/hg19/hg19_decoy/hg19.decoy.fa \
paired \
-nbam ${bam_n} \
-tbam ${bam_t} \
--threads 8 \
--mutect2-vcf ${tumour_id}.mutect2.pass.vcf \
--vardict-vcf ${tumour_id}.vardict.pass.vcf \
--strelka-snv ${tumour_id}.strelka2.snvs.pass.vcf \
--strelka-indel ${tumour_id}.strelka2.indels.pass.vcf
```

To see what goes before **paired** and what goes after:
before: `somaticseq_parallel.py -h`
after: `somaticseq_parallel.py paired -h`

**Comment by ltfang-bina** [comment]
`--threads` should go before `paired` as well.

**Comment by ltfang-bina** [comment]
Looks like the issue is taken care of.

**Comment by ltfang-bina** [comment]
Looks like the issue is taken care of.
