### ISSUE TITLE
freebayes or other callers

### ISSUE THREAD

**Issue by gianfilippo** [bioinform/somaticseq#69]
Hi,

is there a way to include vcfs generated by other callers, like freebayes ?

Thanks
Gianfilippo

**Comment by ltfang-bina** [comment]
Is this for tumor-only or tumor-normal? Is freebayes designed for somatic variants?

**Comment by gianfilippo** [comment]
Hi,

once again, thanks for the prompt reply!

I am using freebayes with tumor-normal matched samples. It seems that it should work for somatic variants.

My question is more general, though. I was wondering whether there was an "easy" way to use other callers. 

I am just putting together a pipeline and can certainly use what somaticseq is designed for.

Thanks
Gianfilippo

**Comment by ltfang-bina** [comment]
I can add a feature to allow any new customized callers to be included in the near future. Before we complete and test that feature, however........

Right now, for the callers that are "officially supported," SomaticSeq may handle each of them differently, some are a bit more complicated than others, some are for legacy reasons. For MuTect2, for instance, it actually grabs some VCF information as training feature, and also look for both SOMATIC and PASS tag to be classified as a "+1" call. 
For LoFreq and Platypus, they're a lot simpler. A call labeled PASS is considered a "+1" call. I'm not familiar with freebayes. If it follows the same label as LoFreq (i.e., PASS calls are considered somatic calls), you may try to pretend that it's LoFreq or Platypus VCF, and feed the freebayes VCF file as `--lofreq-snv freebayes_snv_calls.vcf --lofreq-indel freebayes_indel_calls.vcf` or `--platypus-vcf freebayes_snv_indel_calls.vcf`.

**Comment by gianfilippo** [comment]
thanks. I can definitely try that and look forward to the new feature
