### ISSUE TITLE
somatic mutation spike in pipeline without docker

### ISSUE THREAD

**Issue by gianfilippo** [bioinform/somaticseq#70]
Hi,

is there a way to run the "in silico somatic mutation spike in pipeline" without docker ?

Do you have a version for singularity ? 

Thanks

**Comment by ltfang-bina** [comment]
The mutation spike in pipeline is not exactly a part of somaticseq. The docker scripts just run bamsurgeon (https://github.com/adamewing/bamsurgeon). So you can refer to bamsurgeon's repo to learn how to install and run their software. 
I do have singularity scripts for them, but it's not as well supported but we don't use it much internally so haven't debugged/fixed them routinely: https://github.com/bioinform/somaticseq/tree/master/utilities/singularities/bamSimulator

**Comment by gianfilippo** [comment]
Hi,
thanks for the prompt reply!

I will take a look at both. Thanks

**Comment by gianfilippo** [comment]
Hi,

I am sorry, but I have to reopen this as I have more questions.

I am trying the singularity based scripts. In particular, the BamSimulator_multiThreads.sh. 

It generates 20 numbered dir and a log dir under the OUTPUT  directory.

As far as I understand, I have to run the scripts under each numbered dir and the one under the log dir at the end. Correct ?

Is each script running on multiple cores ? can I submit each script as Slurm job ?

Thanks

**Comment by ltfang-bina** [comment]
Correct. 
Each script under the 20 numbered directories are designed as single-core jobs. I've designed to have those scripts submitted as sun grid engine jobs (e.g., the headers requesting memory, cores, and log file locations, etc. used SGE format), but you can try to submit those scripts as Slurm jobs.

**Comment by ltfang-bina** [comment]
And then the final script under the OUTPUT/log has the command to merge all the bam and VCF files in each of the 20 sub-directories.

**Comment by gianfilippo** [comment]
Great!

Thanks for your help!!
