### ISSUE TITLE
request for examples

### ISSUE THREAD

**Issue by Solenyalyl** [bioinform/somaticseq#71]
Dear author,

Could you add some examples with input data?

thank you

Yulu

**Comment by ltfang-bina** [comment]
Good idea I'll add a tiny demo data set.

**Comment by ltfang-bina** [comment]
You can give these a try, as a demo to see if the installation is complete successfully:
https://github.com/bioinform/somaticseq/tree/v3.nightly/example

**Comment by Solenyalyl** [comment]
thank you~~
