### ISSUE TITLE
Strelka parameters on targeted amplicon panels, single mode (only tumor sample). Using the docker file for run.

### ISSUE THREAD

**Issue by evelingonzalezfeliu** [bioinform/somaticseq#74]
Hi!
First of all, thank you for this awesome tool!

We are using Somaticseq for target panel sequencing data, in consensus mode, using only the tumor sample. For the calculation of sensitivity, we observe the results using the horizon 200 control (somatic variants of FFPE tissue), we have good results, however, the Strelka2 (one of the software used with SomaticSeq) does not identify the SNVs, it is only identifying the Indels.
According to Strelka's recommendations, we added the parameter --targeted, however the results were the same.

We are using the image of the docker for Strelka2.
Is there a difference between the docker and the installed versions of Strelka?

If you can give me any recommendation, I would be very grateful. 

Thank you

The horizon 200 (FFPE control), strelka have only 0 (It is not identifying control variants)
![Captura de pantalla 2019-11-26 a la(s) 09 39 14](https://user-images.githubusercontent.com/37847170/69634295-af13b380-1030-11ea-85bf-6fcddecdb94b.png)

**Comment by ltfang-bina** [comment]
That's odd and I don't know why. Strelka2's germline mode has a VAF cut off threshold but I don't know why it didn't call the 18% VAF SNV.
The Strelka2 in my docker is version 2.9.5. 
Can you show me the command you've used?

**Comment by evelingonzalezfeliu** [comment]
Thanks for the answer!
The comnad for strelka2.9.5

´´´
#!/bin/bash
#$ -o 8_varcall/HD200_S7/logs
#$ -e 8_varcall/HD200_S7/logs
#$ -S /bin/bash
#$ -l h_vmem=6G
set -e
echo -e "Start at `date +"%Y/%m/%d %H:%M:%S"`" 1>&2

docker run -v /:/mnt -u 889 --rm --memory 6G lethalfang/tabix:1.7 bash -c "cat /mnt//home/user/targets/targets.bed | bgzip > /mnt/8_varcall/HD200_S7/targets.bed.gz"
docker run -v /:/mnt -u 889 --rm --memory 6G lethalfang/tabix:1.7 tabix /mnt/8_varcall/HD200_S7/targets.bed.gz

docker run --rm -v /:/mnt -u 889 --memory 6G lethalfang/strelka:2.9.5 \
/opt/strelka/bin/configureStrelkaGermlineWorkflow.py \
--bam=/mnt/7_bqsr/HD200_S7.resorted.bam \
--targeted \
--referenceFasta=/mnt//home/user/genome/hg19.fa  \
--callMemMb=6144 \
 \
--callRegions=/mnt/8_varcall/HD200_S7/targets.bed.gz \
--runDir=/mnt/8_varcall/HD200_S7/Strelka

docker run --rm -v /:/mnt -u 889 --memory 6G lethalfang/strelka:2.9.5 \
/mnt/8_varcall/HD200_S7/Strelka/runWorkflow.py -m local -j 1

echo -e "Done at `date +"%Y/%m/%d %H:%M:%S"`" 1>&2
´´´

**Comment by ltfang-bina** [comment]
That's really odd. I've no idea. You can ask the Strelka2 authors and see if they can figure it out:
https://github.com/Illumina/strelka
