### ISSUE TITLE
slurm vs sge

### ISSUE THREAD

**Issue by cbiitbian** [bioinform/somaticseq#75]
try to use BamsimMutiThread.sh to create own synthetic tumor/normal pair, but out system use slurm not sge.  I substituted "--action qsub" with "--action qsub".  Is this correct?
The process seems to run, but return a lot of errors as "ERROR   2019-12-11 22:12:34.719984      encountered error in mutation spikein: ['chr9_104
14396_10414396_0.479213988448_None']
Traceback (most recent call last):
  File "/usr/local/bamsurgeon/bin/addsnv.py", line 156, in makemut
    mutfail, hasSNP, maxfrac, outreads, mutreads, mutmates = mutation.mutate(args, log, b
amfile, bammate, chrom, min(mutpos_list), max(mutpos_list)+1, mutpos_list, avoid=avoid, m
utid_list=mutid_list, is_snv=True, mutbase_list=mutbase_list, reffile=reffile)
  File "build/bdist.linux-x86_64/egg/bamsurgeon/mutation.py", line 239, in mutate
    assert maxfrac is not None, "Error: could not pile up over region: %s" % region
AssertionError: Error: could not pile up over region: haplo_chr9_10414396_10414397
"
and finally hang at "haplo_chr9_110468931_110468931  aligning addsnv.t
mp/haplo_chr9_110468931_110468931.tmpbam.1067bfd6-fe56-412d-8b73-035e6bc6bcc1.fastq with
bwa mem"

**Comment by ltfang-bina** [comment]
As long as the files are being created, those error messages are just for variants in the random_*.bed file that don't make it into the final synthetic_*.vcf files (i.e., variants attempted but did not make into the final synthetic bam file). 
For details about bamsurgeon, you should contact its author https://github.com/adamewing/bamsurgeon. I've just created some run scripts for it.

**Comment by cbiitbian** [comment]
Thanks for the prompt reply.
How do I pass in other bamsurgeon options, such as –ignorepileup
Xiaopeng

**Comment by ltfang-bina** [comment]
You probably need to either re-write the .sh scripts associated with bamsurgeon or create your own bam mutation pipelines. We didn't really mean to create a comprehensive bamsurgeon feature set.

**Comment by cbiitbian** [comment]
Hi,

I have a question about bamsimulator scenario #1 An ideal example is when you have sequencing replicates of the same normal samples

Is this the same as if I use two copy of the same normal bam, one named “normal”,  the other named “tumor”?

Thanks.

Xiaopeng Bian

**Comment by ltfang-bina** [comment]
Not really. If you sequence the same genome twice, there will be differences between them, including sequencing errors and different reads. Some of the differences will be called as mutations (false positives), so the machine learning model can learn them.
If the same bam file is used, there is no difference between them, so there will be no false positive call.

**Comment by cbiitbian** [comment]
Hi,
Thanks for the explanation!
I followed the example three for multi-thread jobs that merge and then split the input tumor and normal bam files. All ran well except that I had to run the final merge commands manually to merge bam and vcf files.
When I use generated bam and vcf files and ran the training mode in Neurosomatic, I got a “FileNotFoundError: [Errno 2] No such file or directory: 'work_train/dataset/*/candidates*.tsv.idx'” error. Would you please have a look at the attached log file and let me know what are the possible reason why the *tsv.idx did not generated and give me some suggestions how to fix it?
Thanks.
Xiaopeng

**Comment by cbiitbian** [comment]
Hi,
I ran the Bamsimulator multi thread on whole exome data, so I only spike in snv, no sv or indel, but I saw a small (9k) “synthetic_indels.leftAlign.vcf” in the final results.
Because the merge commands did not run correctly, I had to run the merge commands in the log dir after all threads finished, that should be fine?
I just want to make sure the Bamsimulator ran correctly so the problems I had is in the model training step.
Thanks.
Xiaopeng

**Comment by ltfang-bina** [comment]
Sounds like things are fine. If the synthetic_XXX.vcf are not empty, it means those variants were created in the reads. 
In the .sh script, there is a default number of indels. If you want no indel, you would have to explicitly have the parameter `--num-indels 0`.

**Comment by cbiitbian** [comment]
Thank you very much for your help!
I am trying to create a synthetic tumor/normal pair from a pair of hapmap WEX tumor/normal samples with ground truth. I’d like to use them in training a Neusomatic model for SNV calling, in hope that it will improve performance over some of the current popular variant callers, such as Mutect2, MuSE, LoFreq, etc. I’ve learned that Bamsurgeon is not optimal for WEX data, especially for SV spike ins, but that is not what I am interested now.
I followed your example 3 script (attached) created the synthetic pair and Neusomatic script (also attached) to train a model used in Neusomatic calling. But did not get better result than other callers. I think it could be improved by modifying parameters. Would you have a look at the attached script and give me some suggestions which parameters I should change/add to improve the calling performance?
Or if you can point me to any online resources where I can get some information.
Thanks again!
Xiaopeng

**Comment by ltfang-bina** [comment]
Wondering if the bam files you used to spike SNVs are WXS files with broad_MDA_mocha_overlap_cds.bed as the regions? If you use a single pair of WEX while spiking in 30,000 SNVs, the synthetic tumor-normal pairs aren't going to have the "right ratio of true positives and false positives."
I think a more optimal way is to spike in a few thousand into each pair of synthetic WEX data sets, but increase the number of synthetic BAM files, in order to have enough true positives but also enough false positives to have enough training data.

For details of neusomatic, contact https://github.com/bioinform/neusomatic.

**Comment by cbiitbian** [comment]
Hi,
Thank you very much for your suggestions! Yes, I use “broad_MDA_mocha_overlap_cds.bed” as the regions for spliking SNVs into a pair of hapmap WEX tumot/normal files following your Example 3 multi thread process at:
https://github.com/bioinform/somaticseq/tree/master/utilities/dockered_pipelines/bamSimulator

I understand the idea of your suggestion but I don’t know to actually do it.

  1.  You suggest “spike in a few thousand into each pair of synthetic WEX data sets”, you actually mean the real data sets I am using, is that right?
  2.  You suggest “increase the number of synthetic BAM files”, I have four pair of samples, so I could spike in say 8000 SNVs into each of them to generated 4 sets of synthetic tumor/normal pairs?
  3.  “to have enough training data”, how do I feed the multi synthetic data sets generated above into Neosomatic training process? Merge them into a single set first?
Thanks very much!
Xiaopeng

**Comment by ltfang-bina** [comment]
I meant if you want to create 30,000 SNVs for training, you shouldn't create them in a single pair of WXS data set, but rather combine a number of WXS sets. Yes, and then merge them into one.
