### ISSUE TITLE
No succesful mutations?

### ISSUE THREAD

**Issue by adfnih** [bioinform/somaticseq#76]
I'm trying to use your singularity pipeline in singularities/bamSimulator to inject mutation into a bam of the human genome (using BamSimulator_multiThreads.sh).  The creation of the output directories and scripts goes fine, as does splitting the bam file into multiple regions, But when the script gets to actually creating and adding SNVs, I get a long set of errors that take the form:

```
ERROR   2019-12-20 14:50:57.380525      encountered error in mutation spikein: ['1_787825_787825_0.549717808335_None']
Traceback (most recent call last):
  File "/usr/local/bamsurgeon/bin/addsnv.py", line 275, in makemut
    aligners.remap_bam(args.aligner, tmpoutbamname, args.refFasta, alignopts, mutid=hapstr, paired=(not args.single), picardjar=args.picardjar, insane=args.i
nsane)
  File "/usr/local/lib/python2.7/dist-packages/bamsurgeon-1.0-py2.7.egg/bamsurgeon/aligners.py", line 67, in remap_bam
    remap_bwamem_bam(bamfn, threads, fastaref, picardjar, mutid=mutid, paired=paired, insane=insane)
  File "/usr/local/lib/python2.7/dist-packages/bamsurgeon-1.0-py2.7.egg/bamsurgeon/aligners.py", line 211, in remap_bwamem_bam
    raise ValueError("ERROR\t" + now() + "\t" + mutid + "\tbam readcount < fastq readcount, alignment sanity check failed!\n")
ValueError: ERROR       2019-12-20 14:50:57.380429      haplo_1_787825_787825   bam readcount < fastq readcount, alignment sanity check failed!
```
Then at the very end, There is a message that says "no successful mutations", and then samtools complains about not being able to open "unsorted.snvs.added.bam" and the script bails out.   This happened for all the threads.  Do you have any suggestions about where to start trying to debug this?

Thanks

**Comment by ltfang-bina** [comment]
What was the command you've used?

**Comment by adfnih** [comment]
The runfiles were created by the command line:
/usr/local/apps/somaticseq/3.3.0/utilities/singularities/bamSimulator/BamSimulator_multiThreads.sh \
--output-dir        /gpfs/gsfs11/users/fantad/bamsurgeon/multithread-out \
--genome-reference  /gpfs/gsfs11/users/fantad/bamsurgeon/hg19.fa \
--tumor-bam-in      /gpfs/gsfs11/users/fantad/bamsurgeon/tumor.bam \
--tumor-bam-out     syntheticTumor.bam \
--normal-bam-out    syntheticNormal.bam \
--split-proportion  0.5 \
--min-variant-reads 2 \
--threads           24 \
--action  "" \
--num-snvs 10000 \
--num-indels 8000 \
--num-svs 1500 \
--min-vaf 0.0 \
--max-vaf 1.0 \
--left-beta 2 \
--right-beta 5 \
--split-bam \
--indel-realign \
--merge-output-bams

And the line in the runfile that fails is apparently:

singularity exec --bind /:/mnt  --pwd /mnt//gpfs/gsfs11/users/fantad/bamsurgeon/multithread-out/1 docker://lethalfang/bamsurgeon:1.1-3 \
/usr/local/bamsurgeon/bin/addsnv.py \
--snvfrac 0.1 --mutfrac 0.5 --coverdiff 0.9 --procs 1 \
--varfile /mnt//gpfs/gsfs11/users/fantad/bamsurgeon/multithread-out/1/random_sSNV.bed \
--bamfile /mnt//gpfs/gsfs11/users/fantad/bamsurgeon/multithread-out/1/Designated.Tumor.bam \
--reference /mnt//gpfs/gsfs11/users/fantad/bamsurgeon/hg19.fa \
--cnvfile /mnt//gpfs/gsfs11/users/fantad/bamsurgeon/multithread-out/1/sorted.cnvfile.bed.gz \
--outbam /mnt//gpfs/gsfs11/users/fantad/bamsurgeon/multithread-out/1/unsorted.snvs.added.bam \
--mindepth 5 \
--maxdepth 5000 \
--minmutreads 2 \
--seed 7899 \
--picardjar /usr/local/bin/picard.jar \
--ignoresnps --force --tagreads \
--aligner mem

Thanks
