### ISSUE TITLE
RealignerTargetCreator and IndelRealigner steps

### ISSUE THREAD

**Issue by gianfilippo** [bioinform/somaticseq#77]
Hi,

is the IndelRealigner really needed ? 

I am asking since GATK4 does no longer use it. 

Does any of the other callers used by somaticseq need it ?

Thanks
Gianfilippo

**Comment by ltfang-bina** [comment]
It's not so critical. All the modern variant callers do their own realignment. It's more "proper" to be consistent for training vs. testing data, i.e., if you use indel realignment during model building, you should do the same for your other data.

**Comment by gianfilippo** [comment]
Thanks
