### ISSUE TITLE
Error: In training mode, there must be both true positives and false positives in the call set.

### ISSUE THREAD

**Issue by gianfilippo** [bioinform/somaticseq#78]
Hi,
I am getting the error below when I run somaticseq in training mode. Can you please let me know what am I doing wrong ? Thanks

Loading required package: ada
Loading required package: rpart
Remove Consistent_Mates 
Remove Inconsistent_Mates 
[1] "Fitting model..."
[1] "Seed = 21860"
Call:
ada(model_formula, data = train_data, iter = boosting_iters, 
    control = rpart.control(cp = -1, maxdepth = 16, minsplit = 0, 
        xval = 0))

Loss: exponential Method: discrete   Iteration: 500 

Final Confusion Matrix for Data:
          Final Prediction
True value    0    1
         0 5762    0
         1    0    1

Train Error: 0 

Out-Of-Bag Error:  0  iteration= 10 

Additional Estimates of number of iterations:

train.err1 train.kap1 
         2          2 

WARNING: ignoring environment value of R_HOME
Loading required package: ada
Loading required package: rpart
Error: In training mode, there must be both true positives and false positives in the call set.
Execution halted
2020-03-24 21:18:29,861 - SomaticSeq - INFO - Removed: Sample_Test/1.th.input.bed
2020-03-24 21:18:29,863 - SomaticSeq - INFO - Removed sub-directory: Sample_Test/1

**Comment by ltfang-bina** [comment]
Can you check what are the values for the final column, i.e., TrueVariants_or_False in the header?
This is an error that will be raised if the R script cannot find both 0 and 1 in the TrueVariants_or_False column.

**Comment by ltfang-bina** [comment]
Looks the first one was trained and the error was raised on the 2nd one (indel). Please check if there are both 0's and 1's in the indel tsv file.

**Comment by gianfilippo** [comment]
It seems that my Ensemble.sINDEL.tsv have only FalsePositive. Considering also the single true positive in the SNV, is it possible that something went wrong somewhere in the bamsurgeon part of my scripts? or may when I call variants from the spiked BAMs ?

**Comment by ltfang-bina** [comment]
Possibly. Make sure you used the right synthetic tumor and normal bam files, and the right truth snv and truth indel files in your pipeline.

**Comment by gianfilippo** [comment]
I believe I am using the right files. I am wondering whether the coordinates of the true SNVs and INDELs files might be not matching the one in the spiked BAMs. I should probably check a few examples

**Comment by ltfang-bina** [comment]
Usually the SNV positions should be pretty consistent between spike in and the synthetic VCF files. How many SNVs are there in the final snv VCF file? 
For indels, things can be quite different if you don't do left align of the VCF file.

**Comment by gianfilippo** [comment]
I have 3179 SNVs and 609 INDELs
I did do left alignment and used the leftAlign.vcf

**Comment by gianfilippo** [comment]
I now know that this was an issue because of the way I ran this job. Thanks
