### ISSUE TITLE
docker error - docker: Error response from daemon: OCI runtime create failed: container_linux.go:349: starting container process caused "process_linux.go:319: getting the final child's pid from pipe caused \"EOF\"": unknown.

### ISSUE THREAD

**Issue by jeongmeani** [bioinform/somaticseq#82]
Hi, 
using your docker environment and prediction script, i analysis my WES data.
but about a week ago, docker often stops working while printing following message.

`docker: Error response from daemon: OCI runtime create failed: container_linux.go:349: starting container process caused "process_linux.go:319: getting the final child's pid from pipe caused \"EOF\"": unknown.`

i try to search solution of this error, but i could not find anything to solve it.

so do you have some ideas of this?

Best Regards

Jeongmin

**Comment by ltfang-bina** [comment]
At which step did you receive this error? What was your command?

**Comment by jeongmeani** [comment]
at first of the almost job, i faced this error.
my analysis step is ' Use BAMSurgeon to create training data - dream challenge' -> training -> prediction
command is 
**training**
`/data/tools/SomaticSeq_install/utilities/dockered_pipelines/makeSomaticScripts.py paired \
--normal-bam /home/jmkim/somaticseq_training_twist/training_output_KN-128-001-BL1/syntheticNormal_KN-128-001-BL1.bam \
--tumor-bam /home/jmkim/somaticseq_training_twist/training_output_KN-128-001-BL1/syntheticTumor_KN-128-001-BL1.bam \
--genome-reference /data/ref/hg19/hg19.rm.superconfig.fa \
--output-directory /home/jmkim/somaticseq_training_twist/classifier_KN-128-001-BL1 \
--dbsnp-vcf /data/tools/GATK_install/bundle/hg19/dbsnp_138.hg19.vcf \
--truth-snv /home/jmkim/somaticseq_training_twist/training_output_KN-128-001-BL1/synthetic_snvs.vcf \
--truth-indel /home/jmkim/somaticseq_training_twist/training_output_KN-128-001-BL1/synthetic_indels.leftAlign.vcf \
--action 'qsub -l walltime=5:00:00' \
--threads 12 \
--run-mutect2 --run-varscan2 --run-jointsnvmix2 --run-somaticsniper --run-vardict --run-muse --run-lofreq --run-strelka2 --run-somaticseq --train-somaticseq`

**prediction**
`  /data/tools/SomaticSeq_install/utilities/dockered_pipelines/makeSomaticScripts.py paired \
  --normal-bam /data/projects/snubh/WES/02.BAM/5.BQSR_BAM/$N_BAM \
  --tumor-bam /data/projects/snubh/WES/02.BAM/5.BQSR_BAM/$T_BAM \
  --genome-reference /data/ref/hg19/hg19.rm.superconfig.fa \
  -outdir /data/projects/snubh/WES/03.Variant/1.Somaticseq/pair_new/$N_name'.'$T_name \
  --dbsnp-vcf /data/ref/dbsnp/dbsnp_138.hg19.sortByRef.vcf \
  -snvClassifier /home/jmkim/somaticseq_training_twist/classifier_KN-128-001-BL1/Ensemble.sSNV.tsv.ada.Classifier.RData \
  -indelClassifier /home/jmkim/somaticseq_training_twist/classifier_KN-128-001-BL1/Ensemble.sINDEL.tsv.ada.Classifier.RData \
  --action 'qsub -l walltime=100:00:00 -e '$Working_dir'/tmp3 -o '$Working_dir'/tmp3' \
  --threads 12 \
  --somaticseq-algorithm ada \
  --exome \
  --run-mutect2 --run-varscan2 --run-jointsnvmix2 --run-somaticsniper --run-muse --run-vardict --run-lofreq --run-strelka --run-somaticseq`

and many outputs were not made, so i run directly merge.cmd.
and print this error message.

`[jmkim@penta01 KN-128-005-TF1]$ sh logs/mergeResults.2020.06.13T12.43.48.                                                                              543574.cmd`

> Start at 2020/06/15 09:05:06
>docker: Error response from daemon: OCI runtime create failed: container_linux.g                                                                              >o:349: starting container process caused "process_linux.go:319: getting the fina                                                                              >l child's pid from pipe caused \"EOF\"": unknown.

a month ago, when i have used somaticseq it always work successfully.
but a week ago suddenly it makes error.

Best Regards

Jeongmin

**Comment by ltfang-bina** [comment]
Can you copy what's in `logs/mergeResults.2020.06.13T12.43.48.543574.cmd`?

**Comment by ltfang-bina** [comment]
If many outputs were not made.... try run some command like `docker run --rm lethalfang/somaticseq:latest ls /opt/somaticseq` just to make sure docker is still working properly. 
Sometimes docker images may be filling up your drive.

**Comment by jeongmeani** [comment]
Ok ! Thank you.
i attach logs/mergeResults.2020.06.13T12.43.48.543574.cmd.
[mergeResults.2020.06.13T12.43.48.543574.txt](https://github.com/bioinform/somaticseq/files/4777497/mergeResults.2020.06.13T12.43.48.543574.txt)

and i ran the `docker run --rm lethalfang/somaticseq:latest ls /opt/somaticseq`
but it print same error message..

`(base) [root@penta01 somaticseq]# docker run --rm lethalfang/somaticseq:latest ls /opt/s                            omaticseq`
>docker: Error response from daemon: OCI runtime create failed: container_linux.go:349: s                            >tarting container process caused "process_linux.go:319: getting the final child's pid fr                            >om pipe caused \"EOF\"": unknown.

is my server system unstable?

Best Regards

Jeongmin

**Comment by ltfang-bina** [comment]
I'm wondering if your local drive allocated to docker is running out of space. 
Try to see how many docker images are stored locally `docker images`
See how many containers you have locally `docker ps -a`

Remove containers `docker rm CONTAINER_ID`
Remove images 'docker rmi DOCKER_IMAGE`

Then try the simple docker command again `docker run --rm lethalfang/somaticseq:latest ls /opt/somaticseq`

**Comment by jeongmeani** [comment]
after remove some docker image and container, it works!

Thank you very much.

Best Regards

Jeongmin

**Comment by ltfang-bina** [comment]
Docker works again after cleaning up inactive images.
