### ISSUE TITLE
dockered vardict issue

### ISSUE THREAD

**Issue by gianfilippo** [bioinform/somaticseq#83]
Hi,

I am running submit_callers_multiThreads.sh under Singularity using 20 threads.

I am running with various callers available, including VarDict. All the callers seem to be completing. I vardict script fails with the following error:

Start at 2020/07/03 22:02:34
FATAL:   Unable to handle docker://lethalfang/somaticseq:3.5.1 uri: failed to get SHA of docker://lethalfang/somaticseq:3.5.1: Error reading manifest 3.5.1 in docker.io/lethalfang/somaticseq: manifest unknown: manifest unknown

This is because it is trying to run 
somaticseq/utilities/split_mergedBed.py

Can you help me with the error ?

Also, why did you use split_mergedBed.py before VarDict ? this does not seem to be used for the other callers

Thanks

**Comment by ltfang-bina** [comment]
Try it again. There wasn't 3.5.1 in docker hub. I just added it.

**Comment by gianfilippo** [comment]
Hi,

it starts now, but eventually fails. I am attaching the output in a file. The error message is
FATAL:   Failed to initialize runtime engine: engine "" is not found

Any ideas ?
[error.log](https://github.com/bioinform/somaticseq/files/4873088/error.log)

Thanks

**Comment by gianfilippo** [comment]
Hi,

I have an update. I processed three samples. The "FATAL: Failed to initialize runtime engine: engine "" is not found" error is only for the first sample. The other two samples are ok. Can you think of any reason for this ?
The other callers, with the exception of vardict2 (I opened another issue for it), work.
Thanks

**Comment by ltfang-bina** [comment]
What was the command you've used?

**Comment by gianfilippo** [comment]
Hi,

this error is probably caused by causes external to your code. Possibly, the fact that Singularity defaults to the HOME dir for cache and this may cause issues because of limited quota.  After setting the SINGULARITY_CACHEDIR var to a different path it seems ok. If this is indeed the case, I will close this issue.

Thanks for looking into it!

Best

**Comment by gianfilippo** [comment]
Hi,

I am still having an issue. It seems that as soon as one is solved, a new issue comes up....

I am attaching the output from one of the tools. It is the same as for the others. This seem to be happening for Mutect2, Strelka, VarDict, SomaticSniper and JointSNVMix2.
[out.log](https://github.com/bioinform/somaticseq/files/4905539/out.log)

Can you please look into it and tell me what you think ? 

Thanks

**Comment by ltfang-bina** [comment]
Did the singularity tasks run despite the warning, or did it stop running?
I'm no expert in singularities. It seems to be complaining about mounting /home/user in your local environment to /home/user in singularities, because somehow the container already has /home/user/project, either because it was mounted already or reasons that I don't know.

**Comment by gianfilippo** [comment]
Thanks for the prompt reply!!
The ones I pointed out stop running. The warning you are referring to is present also in the ones that complete, and I do not think it is a major issue.
In the file I sent you there is a "panic" line after "copying blob". What do you think ?

**Comment by ltfang-bina** [comment]
It looks similar to this issue: https://github.com/hpcng/singularity/issues/5329, that may be fixed with this answer https://github.com/hpcng/singularity/issues/5329#issuecomment-637595826.

**Comment by gianfilippo** [comment]
thanks!!
I am testing vardict and, so far, it is not stopping. I am really grateful for your help.

**Comment by gianfilippo** [comment]
It seems ok now.
Thanks!
