### ISSUE TITLE
singularity submit_SomaticSeq.sh code error ?

### ISSUE THREAD

**Issue by gianfilippo** [bioinform/somaticseq#85]
Hi,

I got another error at the point where the submit_SomaticSeq.sh gets executed (the singularity version).

The error is 
/var/spool/slurmd/job9700596/slurm_script: line 14: docker: command not found

I checked the submit_SomaticSeq.sh code and it appears that at line 270 you have the following
echo "docker pull lethalfang/somaticseq:${VERSION}" >> $out_script

the 'docker' is not recognized as command, of course.

I replaced it with the following
echo "singularity pull docker://lethalfang/somaticseq:${VERSION}" >> $out_script

but I get the following error
FATAL:   Failed to initialize runtime engine: engine "" is not found

Clearly, what I did is not working. Can you please look into it ?

Thanks

**Comment by ltfang-bina** [comment]
It seemed to work for me `singularity pull docker://lethalfang/somaticseq:3.5.1`, then `singularity exec docker://lethalfang/somaticseq:3.5.1 ls -ls /opt/somaticseq`.

**Comment by gianfilippo** [comment]
Hi,

this is now working. Most of my issues were related to singularity itself. They are not fully solved, but, at least, I can get it to work, with some effort
Thanks
