### ISSUE TITLE
clarification: ada_model_builder_ntChange.R vs ada_model_builder.R

### ISSUE THREAD

**Issue by gianfilippo** [bioinform/somaticseq#89]
Hi,

what is the difference between ada_model_builder_ntChange.R and ada_model_builder.R.

The name of the .RData model file of my first sample has the "ada: string in it, while the new samples show "ntChange". Can you please explain ?

Thanks

**Comment by gianfilippo** [comment]
The .ntChange.Classifier.RData seems to be produced by the call to somaticseq_parallel.py, while the ada.Classifier.RData comes from a direct call to the R script, following the manual. Are the models different at the end ?

**Comment by ltfang-bina** [comment]
The ada_model_builder_ntChange.R script will create extra features for nucleotide changes, i.e., G>C, G>T, etc.
