### ISSUE TITLE
bamSimulator result shows a lot of false positives

### ISSUE THREAD

**Issue by LeiHaoa** [bioinform/somaticseq#92]
Hi，
 I am using _BamSimulator_multiThreads.sh_ to generate training data set with ground truths. but I ran into some problems:
 
- when i use VarDict and Strelka2 to calling the genetated data, the result shows a lot of false positives. is this normal?  
 the script I use BamSimulator_multiThreads.sh :
 ```
${SOMATICSEQ_PATH}/utilities/dockered_pipelines/bamSimulator/BamSimulator_multiThreads.sh \
    --genome-reference  ${REFERNCE} \
    --tumor-bam-in      ${FD_SOURCE}/SRR7890826.sorted.bam \
    --normal-bam-in     ${FD_SOURCE}/SRR7890827.sorted.bam \
    --tumor-bam-out     syntheticTumor.bam \
   --normal-bam-out    syntheticNormal.bam \
   --threads 30 \
    --split-proportion  0.5 \
    --num-snvs          20000 \
    --num-indels        8000 \
    --min-vaf           0.0 \
    --max-vaf           1.0 \
    --left-beta         2 \
    --right-beta        5 \
    --min-variant-reads 2 \
    --output-dir   data/FD/trainingSet_10_15\
    --merge-bam --split-bam --indel-realign --merge-output-bams
```

then I use parallel to ran output .cmd:

`( time parallel --jobs 30 < jobs.jb ) && ( time sudo ${FD}/trainingSet_10_19/logs/mergeFiles.2020-10-19_14-21-35_231130925.cmd)`
jobs.jb list all .cmd file except mergeFiles.cmd

- To verify this tool, I have use SRR7890826.sorted.bam as both --tumor-bam-in and --normal-bam-in, the fasle-positive calling result in vardict and strealka2 also very high.  It's kind of weird, I think, can you explain why? 

- must I use --merge-bam and --split-bam if I want use BamSimulator_multiThreads.sh instead of BamSimulator_singleThreads.sh? even if have two .bam files? 

 - by the way, the SRR7890826.sorted.bam and SRR7890827.sorted.bam is downloaded from (https://sites.google.com/view/seqc2/home/sequencing) you have provided. and I downloaded WGS_FD_N_1 and WGS_FD_N_2, and aligned with bwa-men to hg38.fa reference. did I download the right file ?

many thanks!

**Comment by litaifang** [comment]
Actually, I suggest **not** to use `--merge-bam --split-bam` if you are using WGS_FD_N_1 and WGS_FD_N_2 as the input files. The options `--merge-bam --split-bam` will combine WGS_FD_N_1 and WGS_FD_N_2 into a single bam file, and then randomly split them into a designated tumor and normal. There is no need to do this when you're using two technical replicates of the same **sample** as input bam files. The one designated as "tumor bam" will have in silico mutations spiked into it.
Yes, it's normal to call tens of thousands of false positive somatic mutations in a whole genome sequencing experiment, considering there are 3 billion base positions.

**Comment by LeiHaoa** [comment]
Thank you for your patient answers， but when i delete `--merge-bam --split-bam` in my script, the .cmd file (xxxx/mergeFile.cmd )shows that it only merge normal file, and i only get syntheticTumor.bam and syntheticTumor.bam.bai, is that means the syntheticTumor.bam is tumor file and ${FD_SOURCE}/SRR7890827.sorted.bam is the normal file?? if not , what should i write my script to get syntheticTumor.bam and  syntheticNormal.bam ??
my script is:
```
${SOMATICSEQ_PATH}/utilities/dockered_pipelines/bamSimulator/BamSimulator_multiThreads.sh \
--genome-reference  ${REFERNCE} \
--tumor-bam-in      ${FD_SOURCE}/SRR7890826.sorted.bam \
--normal-bam-in     ${FD_SOURCE}/SRR7890827.sorted.bam \
--tumor-bam-out     syntheticTumor.bam \
--normal-bam-out    syntheticNormal.bam \
--threads 30 \
--split-proportion  0.5 \
--num-snvs          20000 \
--num-indels        8000 \
--min-vaf           0.0 \
--max-vaf           1.0 \
--left-beta         2 \
--right-beta        5 \
--min-variant-reads 2 \
--output-dir       workspace/data/FD/trainingSet_10_19_2 \
--merge-output-bams
```

**Comment by litaifang** [comment]
Mutations will be spiked into SRR7890826.sorted.bam, with the output file named syntheticTumor.bam.
BamSurgeon won't do anything to SRR7890827.sorted.bam in this case, so just use SRR7890827.sorted.bam when you need to do tumor-normal somatic mutation calling (with syntheticTumor.bam as the tumor). 
The normal bam is only there if you want it to do joint indel realignment.

**Comment by LeiHaoa** [comment]
got it! thanks again!
