### ISSUE TITLE
omitted some columns of tsv in somatic_vcf2tsv.py 

### ISSUE THREAD

**Issue by jeongmeani** [bioinform/somaticseq#93]
Hi, 

there are some update of Somaticseq script including **somatic_vcf2tsv.py**.
but i think this update is related to error 'object '**nBAM_Z_Ranksums_MQ**' not found'.

i check somatic_vcf2tsv.py that makes ensemble.tsv and find **nBAM_Z_Ranksums_MQ** column was removed from **out_header** variable.
so i guess this change occurs error like above.

would i change something of my somaticseq run setting?

Best Regards

Jeongmin

**Comment by litaifang** [comment]
As v3.5.0 or later, we have replaced z-scores from scipy's ranksums with p-values from scipy's mannwhitneyu, mostly because the Mann-Whitney U test corrects for discrete values that we have in sequencing metrics. So files before v3.5.0 are incompatible with files produced by v3.5.0 or later.
You can simply stick with an older version like v3.4.2 (https://github.com/bioinform/somaticseq/releases), which is the last version that still uses Z_Ranksums.

**Comment by litaifang** [comment]
Alternatively, if you'd like to use the latest versions, you'd need to re-run SomaticSeq (you will **not** need to re-run the individual somatic mutation callers like MuTect2, etc.).

**Comment by jeongmeani** [comment]
Ok, i try latest version.
thanks again!

**Comment by jeongmeani** [comment]
Hi, again.

now i make classifier using latest version. but it has some issue.
i want to use ada algorithm 
but on tumor_normal_run.py, regardless of algorithm option it uses only somatic_xgboost.py.

so would i insert code that uses ada script?

Best regards.

Jeongmin

**Comment by litaifang** [comment]
What was your command?
It should use ada when if you invoke `--algorithm ada` unless there is a bug I didn't know.

**Comment by litaifang** [comment]
I don't have a working option that directly switches between ada and xgboost. For now, you can still pass it onto the command like
```
makeSomaticScripts.py paired \
--normal-bam       /ABSOLUTE/PATH/TO/normal_sample.bam \
--tumor-bam        /ABSOLUTE/PATH/TO/tumor_sample.bam \
--genome-reference /ABSOLUTE/PATH/TO/GRCh38.fa \
--output-directory /ABSOLUTE/PATH/TO/RESULTS \
--dbsnp-vcf        /ABSOLUTE/PATH/TO/dbSNP.GRCh38.vcf \
--threads          12 \
--container-tech   docker \
--run-mutect2 --run-vardict --run-muse --run-lofreq --run-scalpel --run-strelka2 --run-somaticseq \
--run-workflow \
--somaticseq-arguments '--algorithm ada'
```

The final line will pass `--algorithm ada` to SomaticSeq algorithm. 
Also notice `--run-workflow` will make it run all the scripts automatically.

**Comment by litaifang** [comment]
Sorry. For now actually, when everything is done, just run the ada model separately, i.e., `ada_model_builder_ntChange.R Ensemble.sSNV.tsv` and then `ada_model_builder_ntChange.R Ensemble.sINDEL.tsv`. I'll make the ada option easier to invoke over the weekend or something.

**Comment by jeongmeani** [comment]
Great! 
Thank you for helping me.

and may i  suggest another something.
Latest version of Somaticseq uses subprocess.call to run CMD instead of os.system in previous 3.5 version.
and i have to set the option of qsub walltime to get enough time for run like `--action 'qsub -l walltime=100:00:00 -e '$Working_dir'/tmp -o '$Working_dir'/tmp'`. 
but subprocess.call does not accept this usage. 

so if you don't mind, could you change from subprocess.call to os.system or something to use qsub option?

Best Regards.

Jeongmin

**Comment by litaifang** [comment]
You can try the `latest` branch (i.e., `git checkout latest`). The `--action` argument should work (make sure the quotes are at proper places), and do `--somaticseq-algorithm ada` with the `makeSomaticScripts.py` command. 
Let me know if there are still bugs. If it works, I'll merge it into the master branch.

**Comment by jeongmeani** [comment]
Hi,

after update latest branch, it works perfectly.

Thank you for helping!

Best Regards

Jeongmin

**Comment by litaifang** [comment]
Fixed and will merge the changes into the next release.
