### ISSUE TITLE
Output files when running Consensus mode

### ISSUE THREAD

**Issue by wjianga** [bioinform/somaticseq#94]
Hi,

When I ran SomaticSeq in consensus mode on Mutect2 and VarScan vcf files, I got two Consensus files and two Ensemble files. Am I correct that the consensus files are common variants shared by Mutect2 and VarScan? If so, I have 500000 variants in consensus files while VarScan only called 80000 variants. If not so, would you mind explaining the output files more and how to fix my problem?

Thanks in advance!

**Comment by litaifang** [comment]
Consensus files contain everything. If you want to filter for calls that's been called by **both** VarScan2 and MuTect2, then there should be a field in the INFO column, e.g., MV=1,1 (M=MuTect, V=VarScan).

**Comment by wjianga** [comment]
Thanks!
