### ISSUE TITLE
Prediction output files interpretations

### ISSUE THREAD

**Issue by wjianga** [bioinform/somaticseq#97]
Hi,

I got the output files from the prediction mode run, but I do not know how to interpret them.

1. Which file to look at for true variants? SSeq.Classified.sSNV.tsv or SSeq.Classified.sSNV.vcf?

2. I checked the SSeq.Classified.sSNV.tsv file's "TrueVariant_or_False" column, and it only has "nan" values. How could I fix this?

3. The number of variants in SSeq.Classified.sSNV.vcf is exactly the same as in consensus.vcf. Why is that? I assume SomaticSeq will filter out the false positive?

Thanks!

**Comment by litaifang** [comment]
1. SSeq.Classified.sSNV.tsv with SCORE>0.7 (even better if >0.9) or SSeq.Classified.sSNV.vcf with PASS label are considered high-confidence variant calls. 
2. TrueVariant_or_False is usually nan unless it's training data with truth file attached to it. So nothing wrong with it.
3. By default, every record in the .tsv file is written into the .vcf files for completeness. Filter for "PASS" label for high-confidence calls.

**Comment by wjianga** [comment]
Thanks! I will try filtering the variants based on that. I will update you on how it goes.

**Comment by wjianga** [comment]
I have successfully filtered the variants based on the "PASS" label. Thanks!
